ALTER TABLE users ADD COLUMN IF NOT EXISTS protein_preferences TEXT[] DEFAULT '{}';
ALTER TABLE users ADD COLUMN IF NOT EXISTS carb_preferences TEXT[] DEFAULT '{}';
ALTER TABLE users ADD COLUMN IF NOT EXISTS fat_preferences TEXT[] DEFAULT '{}';
